First version for smart contract
arkadiko-dao/nft-glasses pull request #1
Opened 2021-09-04 12:41 UTC by nieldeckx

- Max 100 NFTs
- Token ID 1-100
- Bonding curve: `(x*x)/2` where x = next token ID
- Token owner can burn token

2021-09-04 13:25 UTC, philipdesmedt requested changes

2021-09-04 13:25 UTC, philipdesmedt commented on clarity/contracts/arkadiko-nft-glasses.clar
> +  (ok (some "https://www.arkadiko.finance/nft-glasses/"))
This can probably be just a JSON, e.g. arkadiko.finance/nft-glasses.json.

Can you make a setter for this so the admin keys can change the token URI?

2021-09-04 13:25 UTC, philipdesmedt commented on clarity/package.json
> +    "email": "philip@arkadiko.com"
this email does not exist, either philip@arkadiko.finance or niel@arkadiko.finance

2021-09-05 09:41 UTC, nieldeckx commented
@philipdesmedt 
- Implemented your feedback
- Updated contract so user can buy NFT with DIKO which is burned

TODO:
- Decide on distribution curve

2021-09-08 07:23 UTC, philipdesmedt commented
@nieldeckx LGTM - gonna merge this. We can do a separate PR to change the bonding curve

2021-09-08 07:24 UTC, merged